micronaut:
  application:
    name: demo
  server:
    port: 9000
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          generator:
            secret: "pleaseChangeThisSecretForANewOne"
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
hello:
  controller:
    path: "/hello"
  config:
    greeting:
      pt: "Olá"
      jp: "Ohayou"

jackson:
  property-naming-strategy: SNAKE_CASE
  serialization:
    writeDatesAsTimestamps: false
    writeDatesWithZoneId: true
    writeDateTimestampsAsNanoseconds: false
  generator:
    writeNumbersAsStrings: true
    writeBigdecimalAsPlain: true
