micronaut:
  application:
    name: demo
  server:
    port: 9000
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          generator:
            secret: "pleaseChangeThisSecretForANewOne"
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
hello:
  controller:
    path: "/hello"
  config:
    greeting:
      pt: "Olá"
      jp: "Ohayou"

jackson:
  property-naming-strategy: SNAKE_CASE
  serialization:
    writeDatesAsTimestamps: false
    writeDatesWithZoneId: true
    writeDateTimestampsAsNanoseconds: false
  generator:
    writeNumbersAsStrings: true
    writeBigdecimalAsPlain: true

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/micronaut
    driverClassName: org.postgresql.Driver
    username: admin
    password: pass
    schema-generate: NONE
    dialect: POSTGRES
jpa:
   default:
    properties:
       hibernate:
         hbm2ddl:
           auto: none
         show_sql: true

liquibase:
  datasources:
    default:
      enabled: true
      change-log: 'classpath:db/liquibase-changelog.xml'
      drop-first: false


flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true